VALID_INTENTS = {
    "greeting",
    "get_time",
    "remember_note",
    "show_notes",
    "set_name",
    "get_name",
    "teach_intent",
    "play_music",
    "open_app",
    "set_reminder",
    "calculate",
    "play_game",
    "debug_route",
    "debug_app_cleanup",
    "debug_app_resolution",
    "debug_match",
    "debug_model",
    "evaluate_model",
    "confirm_intent",
    "deny_intent",
    "show_history",
    "show_conversation",
    "show_reminders",
    "summarize_conversation",
    "show_summaries",
    "search_app_registry",
    "search_memory",
    "semantic_memory_search",
    "debug_memory_search",
    "memory_stats",
    "preview_memory_cleanup",
    "archive_memory_cleanup",
    "search_archive",
    "archive_stats",
    "preview_archive_summary",
    "save_archive_summary",
    "show_archive_summaries",
    "prune_archive",
    "recall_memory",
    "recall_memory_source",
    "set_profile_fact",
    "show_profile",
    "get_profile_fact",
    "coding_help",
    "debug_entity",
    "remember_game_entity",
    "remember_app_entity",
    "show_entities",
    "cleanup_entities",
    "preview_entity_conflicts",
    "resolve_entity_conflict",
    "cleanup_reminders",
    "complete_reminder",
    "reminder_stats",
    "search_reminders",
    "edit_reminder",
    "migrate_reminders",
    "search_reminders_by_due",
    "set_reminder_due",
    "clear_reminder_due",
    "today_reminders",
    "tomorrow_reminders",
    "overdue_reminders",
    "reminder_dashboard",
    "daily_briefing",
    "suggest_next_task",
    "complete_pending_task",
    "skip_pending_task",
    "show_pending_task",
    "start_focus",
    "stop_focus",
    "focus_status",
    "show_focus_sessions",
    "focus_stats",
    "today_focus_stats",
    "focus_stats_for_task",
    "focus_streak",
    "set_focus_goal",
    "show_focus_goal",
    "focus_goal_progress",
    "debug_focus_goal",
    "add_focus_note",
    "show_current_focus_notes",
    "search_focus_sessions",
    "delete_focus_session",
    "cleanup_focus_sessions",
    "search_focus_notes",
    "weekly_focus_stats",
    "best_focus_day",
    "focus_dashboard",
    "register_app",
    "show_app_registry",
    "enable_app_launching",
    "disable_app_launching",
    "show_settings",
    "show_app_launch_history",
    "app_launch_stats",
    "unregister_app",
    "update_registered_app",
    "add_app_alias",
    "show_app_aliases",
    "remove_app_alias",
    "set_default_app",
    "show_default_apps",
    "remove_default_app",
    "app_dashboard",
    "enable_app_launch_confirmation",
    "disable_app_launch_confirmation",
    "show_pending_app_launch",
    "clear_pending_app_launch",
    "allow_app",
    "disallow_app",
    "app_safety_dashboard",
    "preview_app_cleanup",
    "repair_app_cleanup",
    "delete_app_registry_by_index",
    "rename_app_registry_by_index",
    "backup_app_registry",
    "show_app_registry_backups",
    "preview_restore_app_registry_backup",
    "restore_app_registry_backup",
    "preview_app_backup_cleanup",
    "cleanup_app_backups",
    "register_search_folder",
    "show_search_folders",
    "list_folder_files",
    "search_files_by_name",
    "file_info",
    "preview_file",
    "search_text_files",
    "file_search_dashboard",
    "unregister_search_folder",
    "update_search_folder",
    "validate_search_folders",
    "show_file_search_history",
    "file_search_stats",
    "preview_file_search_cleanup",
    "cleanup_file_search_history",
    "preview_file_around",
    "preview_file_range",
    "chat_how_are_you",
    "chat_feeling_statement",
    "chat_need_help",
    "chat_stuck",
    "chat_thanks",
    "chat_goodbye",
    "chat_day_greeting",
    "chat_capabilities",
    "chat_identity",
    "chat_about_user",
    "chat_remember_that",
    "chat_topic_statement",
    "chat_current_topic",
    "chat_clear_topic",
    "chat_explain_last",
    "chat_repeat_last",
    "chat_response_helpful",
    "chat_response_not_helpful",
    "show_response_feedback_stats",
    "show_recent_response_feedback",
    "cleanup_response_feedback",
    "clear_response_feedback",
    "preview_clear_response_feedback",
    "chat_feedback_dashboard",
    "chat_feedback_for_intent",
    "search_response_feedback",
    "filter_response_feedback_by_value",
    "filter_response_feedback_by_group",
    "response_feedback_health",
    "response_feedback_summary",
    "problem_feedback_intents",
    "helpful_feedback_intents",
    "chat_improvement_target",
    "chat_feedback_note",
    "show_feedback_notes",
    "delete_feedback_note",
    "dataset_stats",
    "dataset_intent_counts",
    "dataset_duplicates",
    "dataset_conflicts",
    "dataset_broken_records",
    "dataset_missing_fields",
    "dataset_unknown_intents",
    "dataset_health",
    "dataset_coverage",
    "dataset_low_coverage",
    "dataset_suggestions",
    "dataset_examples_for_intent",
    "dataset_intent_health",
    "dataset_weakest_intent",
    "dataset_strongest_intent",
    "dataset_balance",
    "dataset_suggest_examples_for_intent",
    "dataset_conflicts_for_intent",
    "dataset_conflict_summary",
    "preview_resolve_dataset_conflict",
    "resolve_dataset_conflict",
    "backup_datasets",
    "show_dataset_backups",
    "preview_restore_dataset_backup",
    "restore_dataset_backup",
    "preview_dataset_backup_cleanup",
    "cleanup_dataset_backups",
    "dataset_dashboard",
    "dataset_report",
    "show_memory_result",
    "explain_memory_result",
    "compare_memory_results",
    "clear_memory_results",
    "memory_result_stats",
    "memory_result_summary",
}

CONTROL_INTENTS = {
    "debug_route",
    "debug_app_cleanup",
    "debug_app_resolution",
    "debug_match",
    "debug_model",
    "evaluate_model",
    "teach_intent",
    "confirm_intent",
    "deny_intent",
    "debug_memory_search",
    "debug_entity",
    "complete_pending_task",
    "skip_pending_task",
    "debug_focus_goal",
    "clear_pending_app_launch",
    "dataset_stats",
    "dataset_intent_counts",
    "dataset_duplicates",
    "dataset_conflicts",
    "dataset_broken_records",
    "dataset_missing_fields",
    "dataset_unknown_intents",
    "dataset_health",
    "dataset_coverage",
    "dataset_low_coverage",
    "dataset_suggestions",
    "dataset_examples_for_intent",
    "dataset_intent_health",
    "dataset_weakest_intent",
    "dataset_strongest_intent",
    "dataset_balance",
    "dataset_suggest_examples_for_intent",
    "dataset_conflicts_for_intent",
    "dataset_conflict_summary",
    "preview_resolve_dataset_conflict",
    "resolve_dataset_conflict",
    "backup_datasets",
    "show_dataset_backups",
    "preview_restore_dataset_backup",
    "restore_dataset_backup",
    "preview_dataset_backup_cleanup",
    "cleanup_dataset_backups",
    "dataset_dashboard",
    "dataset_report",
}

CHAT_INTENTS = {
    "chat_how_are_you",
    "chat_feeling_statement",
    "chat_need_help",
    "chat_stuck",
    "chat_thanks",
    "chat_goodbye",
    "chat_day_greeting",
    "chat_capabilities",
    "chat_identity",
    "chat_about_user",
    "chat_remember_that",
    "chat_topic_statement",
    "chat_current_topic",
    "chat_clear_topic",
    "chat_explain_last",
    "chat_repeat_last",
    "chat_response_helpful",
    "chat_response_not_helpful",
    "show_response_feedback_stats",
    "show_recent_response_feedback",
    "cleanup_response_feedback",
    "clear_response_feedback",
    "preview_clear_response_feedback",
    "chat_feedback_dashboard",
    "chat_feedback_for_intent",
    "search_response_feedback",
    "filter_response_feedback_by_value",
    "filter_response_feedback_by_group",
    "response_feedback_health",
    "response_feedback_summary",
    "problem_feedback_intents",
    "helpful_feedback_intents",
    "chat_improvement_target",
    "chat_feedback_note",
    "show_feedback_notes",
    "delete_feedback_note",
}

MEMORY_INTENTS = {
    "remember_note",
    "show_notes",
    "set_name",
    "get_name",
    "show_history",
    "show_conversation",
    "show_reminders",
    "summarize_conversation",
    "show_summaries",
    "search_app_registry",
    "search_memory",
    "semantic_memory_search",
    "memory_stats",
    "preview_memory_cleanup",
    "archive_memory_cleanup",
    "search_archive",
    "archive_stats",
    "preview_archive_summary",
    "save_archive_summary",
    "show_archive_summaries",
    "prune_archive",
    "recall_memory",
    "recall_memory_source",
    "set_profile_fact",
    "show_profile",
    "get_profile_fact",
    "coding_help",
    "remember_game_entity",
    "remember_app_entity",
    "show_entities",
    "cleanup_entities",
    "preview_entity_conflicts",
    "resolve_entity_conflict",
    "cleanup_reminders",
    "complete_reminder",
    "reminder_stats",
    "search_reminders",
    "edit_reminder",
    "migrate_reminders",
    "search_reminders_by_due",
    "set_reminder_due",
    "clear_reminder_due",
    "today_reminders",
    "tomorrow_reminders",
    "overdue_reminders",
    "reminder_dashboard",
    "daily_briefing",
    "suggest_next_task",
    "show_pending_task",
    "start_focus",
    "stop_focus",
    "focus_status",
    "show_focus_sessions",
    "focus_stats",
    "today_focus_stats",
    "focus_stats_for_task",
    "focus_streak",
    "set_focus_goal",
    "show_focus_goal",
    "focus_goal_progress",
    "add_focus_note",
    "show_current_focus_notes",
    "search_focus_sessions",
    "delete_focus_session",
    "cleanup_focus_sessions",
    "search_focus_notes",
    "weekly_focus_stats",
    "best_focus_day",
    "focus_dashboard",
    "register_app",
    "show_app_registry",
    "enable_app_launching",
    "disable_app_launching",
    "show_settings",
    "show_app_launch_history",
    "app_launch_stats",
    "unregister_app",
    "update_registered_app",
    "add_app_alias",
    "show_app_aliases",
    "remove_app_alias",
    "set_default_app",
    "show_default_apps",
    "remove_default_app",
    "app_dashboard",
    "enable_app_launch_confirmation",
    "disable_app_launch_confirmation",
    "show_pending_app_launch",
    "allow_app",
    "disallow_app",
    "app_safety_dashboard",
    "preview_app_cleanup",
    "repair_app_cleanup",
    "delete_app_registry_by_index",
    "rename_app_registry_by_index",
    "backup_app_registry",
    "show_app_registry_backups",
    "preview_restore_app_registry_backup",
    "restore_app_registry_backup",
    "preview_app_backup_cleanup",
    "cleanup_app_backups",
    "register_search_folder",
    "show_search_folders",
    "list_folder_files",
    "search_files_by_name",
    "file_info",
    "preview_file",
    "search_text_files",
    "file_search_dashboard",
    "unregister_search_folder",
    "update_search_folder",
    "validate_search_folders",
    "show_file_search_history",
    "file_search_stats",
    "preview_file_search_cleanup",
    "cleanup_file_search_history",
    "preview_file_around",
    "preview_file_range",
    "show_memory_result",
    "explain_memory_result",
    "compare_memory_results",
    "clear_memory_results",
    "memory_result_stats",
    "memory_result_summary",
}

ACTION_INTENTS = {
    "play_music",
    "play_game",
    "open_app",
    "set_reminder",
    "calculate",
}

SEARCH_IGNORED_INTENTS = {
    "search_memory",
    "semantic_memory_search",
    "debug_memory_search",
    "show_conversation",
    "show_history",
    "show_summaries",
    "evaluate_model",
    "debug_model",
    "debug_match",
    "search_archive",
    "archive_stats",
    "preview_archive_summary",
    "save_archive_summary",
    "show_archive_summaries",
    "prune_archive",
    "archive_memory_cleanup",
    "preview_memory_cleanup",
}

MEMORY_TYPE_PRIORITY = {
    "note": 5,
    "reminder": 5,
    "summary": 4,
    "history": 3,
    "conversation": 2,
    "archive_summary": 3
}

MEMORY_TYPE_ALIASES = {
    "note": "note",
    "notes": "note",
    "reminder": "reminder",
    "reminders": "reminder",
    "history": "history",
    "hist": "history",
    "conversation": "conversation",
    "convo": "conversation",
    "conv": "conversation",
    "summary": "summary",
    "summaries": "summary",
    "archive": "archive_summary",
    "archive_summary": "archive_summary",
    "archived": "archive_summary",
}

INTENT_PATTERNS = {
    "coding_help": [
        "help me code",
        "help me program",
        "teach me coding",
        "teach me programming",
    ],
    "greeting": [
        "hello",
        "hi",
        "hey",
    ],
    "evaluate_model": [
        "evaluate model",
        "test model",
        "model accuracy",
    ],
    "show_profile": [
        "show profile",
        "what do you know about me",
        "my profile",
    ],
    "cleanup_entities": [
        "cleanup entities",
        "clean entities",
        "dedupe entities",
    ],
    "preview_entity_conflicts": [
        "preview entity conflicts",
        "entity conflicts",
        "show entity conflicts",
    ],
    "show_reminders": [
        "show reminders",
        "list reminders",
        "what are my reminders",
    ],
    "cleanup_reminders": [
        "cleanup reminders",
        "clean reminders",
        "dedupe reminders",
    ],
    "reminder_stats": [
        "reminder stats",
        "reminders stats",
        "show reminder stats",
    ],
    "migrate_reminders": [
        "migrate reminders",
        "upgrade reminders",
        "convert reminders",
    ],
    "today_reminders": [
        "today reminders",
        "show today reminders",
        "reminders today",
    ],
    "tomorrow_reminders": [
        "tomorrow reminders",
        "show tomorrow reminders",
        "reminders tomorrow",
    ],
    "overdue_reminders": [
        "overdue reminders",
        "show overdue reminders",
        "late reminders",
    ],
    "reminder_dashboard": [
        "reminder dashboard",
        "reminders dashboard",
        "show reminder dashboard",
    ],
    "daily_briefing": [
        "daily briefing",
        "today briefing",
        "start my day",
        "brief me",
    ],
    "suggest_next_task": [
        "what should i do now",
        "what should i do next",
        "what should i work on",
        "next task",
        "suggest next task",
        "what is next",
    ],
    "complete_pending_task": [
        "done",
        "finished",
        "completed",
        "task done",
    ],
    "skip_pending_task": [
        "skip",
        "skip task",
        "not now",
        "later",
    ],
    "show_pending_task": [
        "pending task",
        "show pending task",
        "what is my pending task",
        "what task is pending",
    ],
    "start_focus": [
        "start focus",
        "focus mode",
        "begin focus",
    ],
    "stop_focus": [
        "stop focus",
        "end focus",
        "exit focus",
    ],
    "focus_status": [
        "focus status",
        "am i focusing",
        "what am i focusing on",
    ],
    "show_focus_sessions": [
        "focus history",
        "show focus history",
        "focus sessions",
    ],
    "focus_stats": [
        "focus stats",
        "show focus stats",
        "focus summary",
    ],
    "today_focus_stats": [
        "today focus stats",
        "focus stats today",
        "today focus summary",
    ],
    "focus_streak": [
        "focus streak",
        "show focus streak",
        "focused days",
    ],
    "show_focus_goal": [
        "show focus goal",
        "focus goal",
        "what is my focus goal",
    ],
    "focus_goal_progress": [
        "focus goal progress",
        "show focus goal progress",
        "today focus goal",
    ],
    "debug_focus_goal": [
        "debug focus goal",
        "debug focus progress",
    ],
    "show_current_focus_notes": [
        "show focus notes",
        "current focus notes",
        "focus notes",
    ],
    "cleanup_focus_sessions": [
        "cleanup focus sessions",
        "clean focus sessions",
        "repair focus sessions",
    ],
    "weekly_focus_stats": [
        "weekly focus stats",
        "focus stats this week",
        "week focus summary",
    ],
    "best_focus_day": [
        "best focus day",
        "top focus day",
        "most focused day",
    ],
    "focus_dashboard": [
        "focus dashboard",
        "show focus dashboard",
        "focus overview",
    ],
    "show_app_registry": [
        "show app registry",
        "registered apps",
        "app registry",
    ],
    "enable_app_launching": [
        "enable app launching",
        "turn on app launching",
    ],
    "disable_app_launching": [
        "disable app launching",
        "turn off app launching",
    ],
    "show_settings": [
        "show settings",
        "settings",
    ],
    "show_app_launch_history": [
        "app launch history",
        "show app launch history",
        "recent app launches",
    ],
    "app_launch_stats": [
        "app launch stats",
        "app stats",
        "show app stats",
    ],
    "show_app_aliases": [
        "show app aliases",
        "app aliases",
    ],
    "show_default_apps": [
        "show default apps",
        "default apps",
    ],
    "app_dashboard": [
        "app dashboard",
        "apps dashboard",
        "app overview",
    ],
    "enable_app_launch_confirmation": [
        "enable app launch confirmation",
        "turn on app launch confirmation",
    ],
    "disable_app_launch_confirmation": [
        "disable app launch confirmation",
        "turn off app launch confirmation",
    ],
    "show_pending_app_launch": [
        "pending app launch",
        "show pending app launch",
        "what app is pending",
    ],
    "clear_pending_app_launch": [
        "clear pending app launch",
        "forget pending app launch",
    ],
    "app_safety_dashboard": [
        "app safety dashboard",
        "app safety",
        "launch safety",
    ],
    "preview_app_cleanup": [
        "preview app cleanup",
        "app cleanup preview",
    ],
    "debug_app_cleanup": [
        "debug app cleanup",
        "show app cleanup details",
    ],
    "repair_app_cleanup": [
        "repair app cleanup",
        "fix app cleanup",
        "cleanup apps",
    ],
    "backup_app_registry": [
        "backup app registry",
        "save app registry backup",
    ],
    "show_app_registry_backups": [
        "show app registry backups",
        "app registry backups",
    ],
    "preview_app_backup_cleanup": [
        "preview app backup cleanup",
        "preview app registry backup cleanup",
    ],
    "cleanup_app_backups": [
        "cleanup app backups",
        "cleanup app registry backups",
        "prune app backups",
    ],
    "show_search_folders": [
        "show search folders",
        "search folders",
    ],
    "file_search_dashboard": [
        "file search dashboard",
        "file dashboard",
        "search folder dashboard",
    ],
    "validate_search_folders": [
        "validate search folders",
        "check search folders",
    ],
    "show_file_search_history": [
        "file search history",
        "show file search history",
        "recent file searches",
    ],
    "file_search_stats": [
        "file search stats",
        "file stats",
        "search file stats",
    ],
    "preview_file_search_cleanup": [
        "preview file search cleanup",
        "file search cleanup preview",
    ],
    "cleanup_file_search_history": [
        "cleanup file search history",
        "cleanup file searches",
        "prune file search history",
    ],
    "chat_how_are_you": [
        "how are you",
        "how are you doing",
        "how do you feel",
        "are you okay",
    ],
    "chat_need_help": [
        "i need help",
        "help me",
        "can you help me",
        "please help me",
    ],
    "chat_stuck": [
        "i am stuck",
        "i'm stuck",
        "i feel stuck",
        "i do not know what to do",
        "i don't know what to do",
    ],
    "chat_thanks": [
        "thank you",
        "thanks",
        "ty",
        "thank you nebula",
        "thanks nebula",
    ],
    "chat_goodbye": [
        "bye",
        "goodbye",
        "see you",
        "see you later",
        "talk later",
        "talk to you later",
    ],
    "chat_day_greeting": [
        "good morning",
        "good afternoon",
        "good evening",
        "morning",
        "afternoon",
        "evening",
    ],
    "chat_capabilities": [
        "what can you do",
        "what are your abilities",
        "what can you help with",
        "what do you do",
    ],
    "chat_identity": [
        "who are you",
        "what are you",
        "are you nebula",
        "what is nebula",
    ],
    "chat_about_user": [
        "do you remember me",
        "tell me about me",
        "what do you remember about me",
    ],
    "chat_current_topic": [
        "what are we talking about",
        "what are we working on",
        "what is the current topic",
        "current topic",
    ],
    "chat_clear_topic": [
        "clear topic",
        "clear current topic",
        "forget current topic",
        "forget topic",
    ],
    "chat_explain_last": [
        "explain that",
        "explain your last response",
        "why did you say that",
        "why that answer",
    ],
    "chat_repeat_last": [
        "repeat that",
        "say that again",
        "what did you say",
        "repeat your last response",
    ],
    "chat_response_helpful": [
        "that helped",
        "that was helpful",
        "this helped",
        "good answer",
    ],
    "chat_response_not_helpful": [
        "that did not help",
        "that didn't help",
        "this did not help",
        "bad answer",
    ],
    "show_response_feedback_stats": [
        "response feedback stats",
        "show response feedback",
        "chat feedback stats",
    ],
    "show_recent_response_feedback": [
        "recent response feedback",
        "show recent response feedback",
        "latest response feedback",
    ],
    "cleanup_response_feedback": [
        "response feedback cleanup",
        "cleanup response feedback",
        "clean response feedback",
    ],
    "clear_response_feedback": [
        "clear response feedback",
        "delete response feedback",
        "remove response feedback",
    ],
    "preview_clear_response_feedback": [
        "preview clear response feedback",
        "preview delete response feedback",
        "response feedback clear preview",
    ],
    "chat_feedback_dashboard": [
        "chat feedback dashboard",
        "response feedback dashboard",
        "feedback dashboard",
    ],
    "response_feedback_health": [
        "response feedback health",
        "check response feedback",
        "response feedback check",
    ],
    "response_feedback_summary": [
        "response feedback summary",
        "summarize response feedback",
        "chat feedback summary",
    ],
    "problem_feedback_intents": [
        "problem feedback intents",
        "bad feedback intents",
        "not helpful intents",
    ],
    "helpful_feedback_intents": [
        "helpful feedback intents",
        "good feedback intents",
        "positive feedback intents",
    ],
    "chat_improvement_target": [
        "what should you improve",
        "what do you need to improve",
        "what should nebula improve",
        "where are you weak",
    ],
    "show_feedback_notes": [
        "show feedback notes",
        "feedback notes",
        "response feedback notes",
    ],
    "dataset_stats": [
        "dataset stats",
        "training data stats",
        "show dataset stats",
    ],
    "dataset_intent_counts": [
        "dataset intent counts",
        "training intent counts",
        "intent data counts",
    ],
    "dataset_duplicates": [
        "dataset duplicates",
        "training duplicates",
        "duplicate examples",
    ],
    "dataset_conflicts": [
        "dataset conflicts",
        "training conflicts",
        "conflicting examples",
    ],
    "dataset_broken_records": [
        "dataset broken records",
        "broken dataset records",
        "show broken records",
    ],
    "dataset_missing_fields": [
        "dataset missing fields",
        "missing dataset fields",
        "training missing fields",
    ],
    "dataset_unknown_intents": [
        "dataset unknown intents",
        "unknown dataset intents",
        "training unknown intents",
    ],
    "dataset_health": [
        "dataset health",
        "training data health",
    ],
    "dataset_dashboard": [
        "dataset dashboard",
        "training dashboard",
        "training data dashboard",
    ],
    "dataset_coverage": [
        "dataset coverage",
        "training coverage",
        "intent coverage",
    ],
    "dataset_low_coverage": [
        "dataset low coverage",
        "low training coverage",
        "low intent coverage",
    ],
    "dataset_suggestions": [
        "dataset suggestions",
        "training suggestions",
        "suggest training examples",
    ],
    "dataset_weakest_intent": [
        "dataset weakest intent",
        "weakest intent",
        "least trained intent",
    ],
    "dataset_strongest_intent": [
        "dataset strongest intent",
        "strongest intent",
        "most trained intent",
    ],
    "dataset_balance": [
        "dataset balance",
        "training balance",
        "intent balance",
    ],
    "dataset_conflict_summary": [
        "dataset conflict summary",
        "training conflict summary",
        "conflict summary",
    ],
    "backup_datasets": [
        "backup datasets",
        "backup training data",
        "backup dataset files",
    ],
    "show_dataset_backups": [
        "show dataset backups",
        "dataset backups",
        "training backups",
    ],
    "preview_dataset_backup_cleanup": [
        "preview dataset backup cleanup",
        "dataset backup cleanup preview",
    ],
    "cleanup_dataset_backups": [
        "dataset backup cleanup",
        "cleanup dataset backups",
        "clean dataset backups",
    ],
    "dataset_report": [
        "dataset report",
        "training report",
        "training data report",
    ],
    "clear_memory_results": [
        "clear memory results",
        "clear saved memory results",
        "forget memory results",
    ],
    "memory_result_stats": [
        "memory result stats",
        "saved memory result stats",
        "memory search result stats",
    ],
    "memory_result_summary": [
        "memory result summary",
        "summarize memory results",
        "memory search summary",
    ],
}

INTENT_PREFIXES = {
    "debug_route": [
        "debug route ",
    ],
    "debug_memory_search": [
        "debug memory ",
    ],
    "debug_model": [
        "debug model ",
    ],
    "debug_app_resolution": [
        "debug app ",
    ],
    "debug_match": [
        "debug ",
    ],
    "teach_intent": [
        "teach ",
    ],
    "set_profile_fact": [
        "remember profile ",
    ],
    "chat_remember_that": [
        "remember that ",
    ],
    "remember_note": [
        "remember ",
    ],
    "search_app_registry": [
        "search apps ",
        "find app ",
    ],
    "search_memory": [
        "search memory ",
    ],
    "semantic_memory_search": [
        "semantic memory ",
    ],
    "search_archive": [
        "search archive ",
    ],
    "recall_memory": [
        "what do you remember about ",
    ],
    "recall_memory_source": [
        "recall notes about ",
        "recall history about ",
        "recall archive about ",
    ],
    "get_profile_fact": [
        "what is my ",
        "what's my ",
    ],
    "debug_entity": [
        "debug entity ",
    ],
    "remember_game_entity": [
        "remember game ",
    ],

    "remember_app_entity": [
        "remember app ",
    ],
    "show_entities": [
        "show entities",
        "known entities",
        "what entities do you know",
    ],
    "resolve_entity_conflict": [
        "resolve entity ",
    ],
    "calculate": [
        "calculate ",
        "what is ",
        "what's ",
    ],
    "complete_reminder": [
        "complete reminder ",
        "done reminder ",
        "finish reminder ",
    ],
    "search_reminders_by_due": [
        "show reminders due ",
        "search reminders due ",
        "find reminders due ",
    ],
    "search_reminders": [
        "search reminders ",
        "find reminder ",
    ],
    "edit_reminder": [
        "edit reminder ",
        "change reminder ",
        "update reminder ",
    ],
    "set_reminder_due": [
        "set reminder ",
    ],
    "clear_reminder_due": [
        "clear reminder ",
    ],
    "focus_stats_for_task": [
        "focus stats for ",
        "focus summary for ",
    ],
    "set_focus_goal": [
        "set focus goal ",
    ],
    "add_focus_note": [
        "focus note ",
    ],
    "search_focus_sessions": [
        "search focus ",
        "find focus ",
    ],
    "delete_focus_session": [
        "delete focus session ",
        "remove focus session ",
    ],
    "search_focus_notes": [
        "search focus notes ",
        "find focus notes ",
    ],
    "register_app": [
        "register app ",
    ],
    "delete_app_registry_by_index": [
        "delete app registry ",
        "remove app registry ",
    ],
    "unregister_app": [
        "unregister app ",
        "remove app ",
    ],
    "update_registered_app": [
        "update app ",
        "change app ",
    ],
    "add_app_alias": [
        "alias app ",
    ],
    "remove_app_alias": [
        "remove app alias ",
        "delete app alias ",
    ],
    "set_default_app": [
        "set default app ",
    ],
    "remove_default_app": [
        "remove default app ",
        "delete default app ",
    ],
    "allow_app": [
        "allow app ",
    ],
    "disallow_app": [
        "disallow app ",
        "block app ",
    ],
    "rename_app_registry_by_index": [
        "rename app registry ",
    ],
    "preview_restore_app_registry_backup": [
        "preview app registry restore ",
    ],
    "restore_app_registry_backup": [
        "restore app registry backup ",
    ],
    "register_search_folder": [
        "register search folder ",
    ],
    "list_folder_files": [
        "list files ",
        "show files ",
    ],
    "search_files_by_name": [
        "search files ",
        "find files ",
    ],
    "file_info": [
        "file info ",
        "show file info ",
    ],
    "preview_file": [
        "preview file ",
        "read file preview ",
    ],
    "search_text_files": [
        "search text ",
        "search inside files ",
    ],
    "unregister_search_folder": [
        "unregister search folder ",
        "remove search folder ",
    ],
    "update_search_folder": [
        "update search folder ",
        "change search folder ",
    ],
    "preview_file_search_cleanup": [
        "preview file search cleanup ",
        "file search cleanup preview ",
    ],
    "cleanup_file_search_history": [
        "cleanup file search history ",
        "cleanup file searches ",
        "prune file search history ",
    ],
    "preview_file_around": [
        "preview around ",
        "preview file around ",
    ],
    "preview_file_range": [
        "preview file range ",
    ],
    "chat_feeling_statement": [
        "i feel ",
        "i am feeling ",
        "i am ",
    ],
    "chat_topic_statement": [
        "i am learning ",
        "i'm learning ",
        "we are learning ",
        "we are working on ",
    ],
    "chat_feedback_for_intent": [
        "feedback for ",
    ],
    "search_response_feedback": [
        "search feedback ",
        "search response feedback ",
    ],
    "filter_response_feedback_by_value": [
        "feedback value ",
    ],
    "filter_response_feedback_by_group": [
        "feedback group ",
    ],
    "chat_feedback_note": [
        "feedback note ",
    ],
    "delete_feedback_note": [
        "delete feedback note ",
        "remove feedback note ",
    ],
    "dataset_examples_for_intent": [
        "dataset examples ",
        "training examples ",
    ],
    "dataset_intent_health": [
        "dataset intent health ",
        "training intent health ",
    ],
    "dataset_suggest_examples_for_intent": [
        "suggest examples for ",
        "suggest training for ",
    ],
    "dataset_conflicts_for_intent": [
        "dataset conflicts for ",
        "training conflicts for ",
    ],
    "preview_resolve_dataset_conflict": [
        "preview resolve conflict ",
    ],
    "resolve_dataset_conflict": [
        "resolve conflict ",
    ],
    "preview_restore_dataset_backup": [
        "preview restore dataset backup ",
    ],
    "restore_dataset_backup": [
        "restore dataset backup ",
    ],
    "show_memory_result": [
        "show memory result ",
        "memory result ",
    ],
    "explain_memory_result": [
        "explain memory result ",
    ],
    "compare_memory_results": [
        "compare memory results ",
    ],
}

PREFIX_INTENT_ORDER = [
    "preview_restore_dataset_backup",
    "restore_dataset_backup",
    "preview_resolve_dataset_conflict",
    "resolve_dataset_conflict",
    "dataset_conflicts_for_intent",
    "dataset_suggest_examples_for_intent",
    "dataset_intent_health",
    "dataset_examples_for_intent",
    "debug_route",
    "debug_memory_search",
    "debug_app_resolution",
    "debug_entity",
    "debug_model",
    "debug_match",
    
    "compare_memory_results",
    "explain_memory_result",
    "show_memory_result",

    "search_reminders_by_due",
    "search_reminders",

    "search_focus_notes",
    "search_focus_sessions",

    "preview_restore_app_registry_backup",
    "restore_app_registry_backup",

    "delete_app_registry_by_index",
    "rename_app_registry_by_index",

    "register_search_folder",
    "unregister_search_folder",
    "update_search_folder",
    
    "preview_file_search_cleanup",
    "cleanup_file_search_history",
    "preview_file_around",
    "preview_file_range",

    "search_text_files",
    "search_files_by_name",
    "file_info",
    "preview_file",
    "list_folder_files",

    "set_profile_fact",
    "remember_game_entity",
    "remember_app_entity",
    "chat_remember_that",
    "remember_note",

    "recall_memory_source",
    "recall_memory",

    "clear_reminder_due",
    "set_reminder_due",
    "complete_reminder",
    "edit_reminder",

    "set_default_app",
    "remove_default_app",
    "add_app_alias",
    "remove_app_alias",
    "update_registered_app",
    "unregister_app",
    "register_app",
    "search_app_registry",
    "allow_app",
    "disallow_app",

    "focus_stats_for_task",
    "set_focus_goal",
    "add_focus_note",
    "delete_focus_session",
    
    "delete_feedback_note",
    "chat_feedback_note",
    "filter_response_feedback_by_group",
    "filter_response_feedback_by_value",
    "chat_topic_statement",
    "search_response_feedback",
    "chat_feedback_for_intent",
    "chat_feeling_statement",

    "get_profile_fact",
    "calculate",
]

PROFILE_KEY_ALIASES = {
    "favorite language": "favorite_language",
    "programming language": "favorite_language",
    "favorite programming language": "favorite_language",
    "favorite coding language": "favorite_language",
    "coding language": "favorite_language",

    "goal": "goal",
    "main goal": "goal",
    "current goal": "goal",
    "project goal": "goal",
    "what i am working toward": "goal",

    "mood": "mood",
    "current mood": "mood",

    "name": "name",
}

KNOWN_GAMES = {
    "minecraft",
    "valorant",
    "roblox",
    
}

KNOWN_APPS = {
    "chrome",
    "vscode",
    "notepad",
}

